### PR TITLE
Fix composed components order after rerender

### LINKED ISSUE #123: bug with compose
on each parent rerender swaps props in children component

[example](https://codesandbox.io/s/py84vwo43m)

### PR DESCRIPTION
**Pull request by jeetiss**
array.reverse is not a pure function, so the order of arguments in children is broken when re-rendering

fix #123

### CODE REVIEW

**Comment by TrySound** [comment]
Could you add test for this case?

File: src/utils/compose.js [hunk 1]
```diff
@@ -4,32 +4,34 @@ import renderProps from './renderProps'
...
+  
   return composedProps => {
     // Stack children arguments recursively and pass
     // it down until the last component that render children
     // with these stacked arguments
     function stackProps(i, elements, propsList = []) {
       const element = elements[i]
       const isTheLast = i === 0
-
+
```
Comment (TrySound) [inline src/utils/compose.js]: What these spaces for?

**Comment by jeetiss** [comment]
@TrySound yep

File: tests/utils/compose.test.js [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+
+        return (
+          // hard rerender
+          <CounterToggle key={on} render={renderFn} />
+        )
+      }}
+    </Toggle>
+  )
+
+  expect(lastCallProps[0].count).toBe(0)
```
Comment (TrySound) [inline tests/utils/compose.test.js]: You may use mock function like here https://github.com/renatorib/react-powerplug/blob/master/tests/components/Active.test.js#L7
```js
expect(renderFn).lastCalledWith(
  expect.objectContaining({ count: 0 })
  expect.objectContaining({ on: false })
)
```
